########################################################################################
#         ____  ____  _     _  ____  _  _____ ___  _
#        / ___\/  _ \/ \   / \/  _ \/ \/__ __\\  \//
#        |    \| / \|| |   | || | \|| |  / \   \  /
#        \___ || \_/|| |_/\| || |_/|| |  | |   / /
#        \____/\____/\____/\_/\____/\_/  \_/  /_/
#
########################################################################################
#
#               Solidity Loader Configuration
# made with <3 by the Solidity Team!
#
# This is the SolidityLoader configuration. It handles the core properties of Solidity
# which changes how Solidity works and how the addons are run.
#
# Configuring this wrong will cause the plugin to break so be aware.
#
########################################################################################

config-version: 1