name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome! Thanks for creating an issue. Your issue will be resolved by the contributors, members and the SolidityTeam later on.'
        pr-message: 'Welcome! Thanks for creating a Pull Request. The pull request should be reviewed by the Solidity team.'
